name: Deploy Slidev to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
  packages: read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Authenticate with GitHub Package Registry
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.xebia_npm_repo_pat }}" > ~/.npmrc

      - name: Install dependencies using package-lock.json
        run: npm ci --legacy-peer-deps

      - name: Build project
        run: npm run build

      - name: remove REAMDE folder
        run: rm -rfd ./dist/README

      - name: move (wrapper) slide to root
        run: mv ./dist/slides/* ./dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  # Deployment job
  deploy:
    environment:
      name: github-pages
      #url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
